### PR TITLE
Dockerize homegames-web

### PR DESCRIPTION
**Pull request by reedalex**
Adds Dockerfile and instructions on how to run the frontend of homegames
with Docker.

Follow them to have the entirety of this project running in a background
container that can communicate with your local machine and homegames core
(dockerized or non-dockerized homegames core)

### CODE REVIEW

**Comment by reedalex** [comment]
Test it with the README directions fellers:

```
1. Navigate to root directory of homegames project

2. Run `docker build -t homegames-web .`

3. Run `docker run -dp 80:80 homegames-web`

4. That's it! The docker container should be up and running, and exposed/published on port 80 (localhost) on whatever machine you ran the above commands on
```

**Comment by reedalex** [comment]
I'd recommend fully testing it by running the docker steps for both this and https://github.com/homegamesio/homegames/pull/30

then playing around in localhost

**Comment by prosif** [comment]
This is awesome, thanks @reedalex! 

Looks good to me, but I'm going to test this weekend before I submit a proper review

**Review by YazeedLoonat — APPROVED** [review]
with the changes to the readme this looks like its working
LGTM!

**Pull request merged**
